AWSTemplateFormatVersion: 2010-09-09

Description: Enforce KMS key encryption for S3 buckets

Resources:
  SimpleBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: simple-bucket-04-2025

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SimpleBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: DenyUnEncryptedObjectUploads
            Effect: Deny
            Principal: "*"
            Action: s3:PutObject
            Resource: !Sub "${SimpleBucket.Arn}/*"
            Condition:
              StringNotEquals:
                "s3:x-amz-server-side-encryption": "aws:kms"
