AWSTemplateFormatVersion: 2010-09-09

Description: The configuration deploys an EC2 instance to a given availability zone.

Parameters:
  InstanceType:
    Type: String
    Description: EC2 instance type
    AllowedValues:
      - t2.micro
      - t3.micro
    Default: t2.micro
  AvailabilityZone:
    Type: String
    Description: Availability Zone for EC2 Instance
  WebSecGroupId:
    Type: String
    Description: Security Group ID
  InstanceName:
    Type: String
    Description: Instance name

Mappings:
  Ec2MachineImages: # All Amazon Linux 2 AMI (HVM) - 64-bit (x86)
    eu-west-1:
      ImageId: "ami-04f87c366aa353bc5"
    eu-west-2:
      ImageId: "ami-0fa3603ea544e5bf9"
    eu-west-3:
      ImageId: "ami-0f139a4a2cdfff8d1"

Resources:
  SimpleInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - Ec2MachineImages
        - !Ref "AWS::Region"
        - ImageId
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
        - !Ref WebSecGroupId
      AvailabilityZone: !Ref AvailabilityZone
      Tags:
        - Key: Name
          Value: !Ref InstanceName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y

          ## Install Nginx
          sudo amazon-linux-extras install nginx1 -y
          sudo service nginx start

          # Enable Nginx to Start on Boot
          sudo systemctl enable nginx

          echo "<h3>Hello world from $(hostname -f) in ${AvailabilityZone} </h3>" > /usr/share/nginx/html/index.html

Outputs:
  PublicIp:
    Description: Public IP of the EC2 instance
    Value: !GetAtt SimpleInstance.PublicIp
  InstanceId:
    Description: InstanceId of the EC2 instance
    Value: !Ref SimpleInstance
