AWSTemplateFormatVersion: 2010-09-09

Description: This template provision a Firehose stream with a Data Stream as it's source and a S3 bucket as it's delivery destination

Resources:
  DataStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: DmStream
      StreamModeDetails:
        StreamMode: PROVISIONED # or ON_DEMAND
      ShardCount: 1

  DestinationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: firehose-delivery-destination

  FirehoseRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: FirehoseRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: FirehoseS3Policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: AllowKinesisDataStreamSource
                Effect: Allow
                Action:
                  - kinesis:GetRecords
                  - kinesis:GetShardIterator
                  - kinesis:DescribeStream
                  - kinesis:ListStreams
                  - kinesis:SubscribeToShard
                Resource: !GetAtt DataStream.Arn
              - Sid: AllowS3Destination
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt DestinationBucket.Arn
                  - !Sub ${DestinationBucket.Arn}/*

  FirehoseStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: DemoDeliveryStream
      DeliveryStreamType: KinesisStreamAsSource # or DatabaseAsSource, DirectPut, MSKAsSource
      KinesisStreamSourceConfiguration:
        KinesisStreamARN: !GetAtt DataStream.Arn
        RoleARN: !GetAtt FirehoseRole.Arn
      S3DestinationConfiguration:
        BucketARN: !GetAtt DestinationBucket.Arn
        RoleARN: !GetAtt FirehoseRole.Arn
        Prefix: demo-firehose/
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 1
        CompressionFormat: UNCOMPRESSED # or GZIP, ZIP, Snappy, HADOOP_SNAPPY
        ErrorOutputPrefix: failed/
