AWSTemplateFormatVersion: 2010-09-09

Description: Solution to process long running jobs using Queues, Step Function, and Lambdas.

Resources:
  EventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      Name: Daily1AmTrigger
      Description: Invoke the DataPreparationFunc at 1am daily
      ScheduleExpression: "cron(35 12 * * ? *)" # 12:15 every day London time
      State: ENABLED
      Targets:
        - Arn: !ImportValue Workers-DataPreparationFuncArn
          Id: DataPreparationFunc

  DataPreparationLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !ImportValue Workers-DataPreparationFuncName
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt EventBridgeRule.Arn

  StepFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: StepFunctionExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: AllowLogs
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Sid: AllowFuncInvoke
                Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !ImportValue Workers-PdfGenerationFuncArn
                  - !ImportValue Workers-PdfMailerFuncArn

  PdfGenStepFunc:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn: !GetAtt StepFunctionRole.Arn
      DefinitionString: !Sub
        - |-
          {
            "Comment": "Step Function to process SQS queue until empty",
            "StartAt": "PdfGeneration",
            "States": {
              "PdfGeneration": {
                "Type": "Task",
                "Resource": "${PdfGenerationFuncArn}",
                "Parameters": {
                  "queueUrl": "${QueueUrl}"
                },
                "Next": "IsQueueEmpty"
              },
              "IsQueueEmpty": {
                "Type": "Choice",
                "Choices": [
                  {
                    "Variable": "$.messageCount",
                    "NumericEquals": 0,
                    "Next": "QueueEmpty"
                  }
                ],
                "Default": "WaitAndRetry"
              },
              "WaitAndRetry": {
                "Type": "Wait",
                "Seconds": 120,
                "Next": "PdfGeneration"
              },
              "QueueEmpty": {
                "Type": "Pass",
                "End": true
              }
            }
          }
        - PdfGenerationFuncArn: !ImportValue Workers-PdfGenerationFuncArn
          QueueUrl: "empty"

  PdfMailerStepFunc:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn: !GetAtt StepFunctionRole.Arn
      DefinitionString: !Sub
        - |-
          {
            "Comment": "Step Function to process SQS queue until empty",
            "StartAt": "PdfMailer",
            "States": {
              "PdfMailer": {
                "Type": "Task",
                "Resource": "${PdfMailerFuncArn}",
                "Parameters": {
                  "queueUrl": "${QueueUrl}"
                },
                "Next": "IsQueueEmpty"
              },
              "IsQueueEmpty": {
                "Type": "Choice",
                "Choices": [
                  {
                    "Variable": "$.messageCount",
                    "NumericEquals": 0,
                    "Next": "QueueEmpty"
                  }
                ],
                "Default": "WaitAndRetry"
              },
              "WaitAndRetry": {
                "Type": "Wait",
                "Seconds": 120,
                "Next": "PdfMailer"
              },
              "QueueEmpty": {
                "Type": "Pass",
                "End": true
              }
            }
          }
        - PdfMailerFuncArn: !ImportValue Workers-PdfMailerFuncArn
          QueueUrl: "empty"
