AWSTemplateFormatVersion: 2010-09-09

Description: Provisions resources for local testing only. Not part of the main solution.
# This template creates resources that can be used to isolate the testing of
# the different lambda function code in the processor NestJS application.
# The Queue URLs and Bucket name can be added to the local .env file for testing purposes.

Resources:
  LocalStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: local-job-processor-04-2025

  LocalPdfGenerationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: LocalPdfGenerationQueue

  LocalPdfMailerQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: LocalPdfMailerQueue

Outputs:
  LocalPdfGenerationQueueUrl:
    Description: URL of the PDF generation SQS Queue
    Value: !Ref LocalPdfGenerationQueue
  LocalLocalPdfMailerQueueUrl:
    Description: URL of the PDF Mailer SQS Queue
    Value: !Ref LocalPdfMailerQueue
  LocalStorageBucket:
    Description: URL of the S3 Bucket
    Value: !Ref LocalStorageBucket
