AWSTemplateFormatVersion: 2010-09-09

Description: Create a EBS volume an attach to EC2 instance

Parameters:
  Az:
    Type: String
    Description: Availability zone
    Default: eu-west-2a
  ImageId:
    Type: String
    Description: EC2 AMI
    Default: ami-0abb41dc69b6b6704 # Amazon Linux 2 AMI 64-bit (x86)
  InstanceType:
    Type: String
    Description: EC2 Instance type
    AllowedValues:
      - t2.micro
      - t3.micro
    Default: t2.micro

Resources:
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: WebSecGroup
      GroupDescription: Security group to allow web access
      SecurityGroupIngress:
        - Description: Allow HTTP access
          IpProtocol: TCP
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"

  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      AvailabilityZone: !Ref Az
      SecurityGroups:
        - !Ref WebSecurityGroup
      Tags:
        - Key: Name
          Value: EbsDemoInstance
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Update the instance

          sudo yum update -y

          ## Install Nginx
          sudo amazon-linux-extras install nginx1 -y
          sudo service nginx start

          # Enable Nginx to start at Boot time
          sudo chkconfig nginx o

  EbsVolume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: !Ref Az
      Size: 10
      VolumeType: gp3
      Encrypted: true
      Tags:
        - Key: Name
          Value: DemoEbsVolume

  Ec2InstanceEbsVolumeAttach:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      Device: /dev/xvdb
      InstanceId: !Ref Ec2Instance
      VolumeId: !Ref EbsVolume

Outputs:
  VolumeId:
    Description: EBS volumn ID
    Value: !Ref EbsVolume
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref Ec2Instance
  PublicId:
    Description: EC2 public IP
    Value: !GetAtt Ec2Instance.PublicIp
