AWSTemplateFormatVersion: 2010-09-09

Description: This template creates S3 Access Points for 3 IAM group to object with particular prefixes.

Parameters:
  BucketName:
    Type: String
    Description: Bucket name for the S3 bucket
    Default: simple-access-demo-13-04
  ExternalUserArn:
    Type: String
    Description: ARN of an external user
  SalesUserArn:
    Type: String
    Description: ARN of a user in Sales department
  FinanceUserArn:
    Type: String
    Description: ARN of a user in Finance department
  SalesAccessPointName:
    Type: String
    Default: sales-access
    AllowedValues: [sales-access]
  FinanaceAccessPointName:
    Type: String
    Default: finance-access
    AllowedValues: [finance-access]
  SalesPrefix:
    Type: String
    Default: sales
  FinancePrefix:
    Type: String
    Default: finance

Resources:
  DemoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DemoBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - s3:ListBucket
              - s3:GetObject
              - s3:PutObject
            Resource:
              - !GetAtt DemoBucket.Arn
              - !Sub ${DemoBucket.Arn}/*
            Condition:
              StringEquals:
                s3:DataAccessPointAccount: !Ref AWS::AccountId

  ExternalRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ExternalRole
      Description: Role to be Assumed by a third party IAM user
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref ExternalUserArn
            Action: sts:AssumeRole

  SalesAccessPoint:
    Type: AWS::S3::AccessPoint
    Properties:
      Name: !Ref SalesAccessPointName
      Bucket: !Ref DemoBucket
      Policy:
        Version: 2012-10-17
        Statement:
          - Sid: SalesAccessPointAccess
            Effect: Allow
            Principal:
              AWS:
                - !Ref SalesUserArn
                - !GetAtt ExternalRole.Arn
            Action:
              - s3:ListBucket
            Resource:
              - !Sub arn:${AWS::Partition}:s3:${AWS::Region}:${AWS::AccountId}:accesspoint/${SalesAccessPointName}
            Condition:
              StringLike:
                s3:prefix:
                  - !Sub ${SalesPrefix}/*
          - Sid: ReadWriteForSales
            Effect: Allow
            Principal:
              AWS:
                - !Ref SalesUserArn
                - !GetAtt ExternalRole.Arn
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
            Resource:
              - !Sub arn:${AWS::Partition}:s3:${AWS::Region}:${AWS::AccountId}:accesspoint/${SalesAccessPointName}/object/${SalesPrefix}/*

  FinanceAccessPoint:
    Type: AWS::S3::AccessPoint
    Properties:
      Name: !Ref FinanaceAccessPointName
      Bucket: !Ref DemoBucket
      Policy:
        Version: 2012-10-17
        Statement:
          - Sid: FinanceAccessPointAccess
            Effect: Allow
            Principal:
              AWS:
                - !Ref FinanceUserArn
                - !GetAtt ExternalRole.Arn
            Action:
              - s3:ListBucket
            Resource:
              - !Sub arn:${AWS::Partition}:s3:${AWS::Region}:${AWS::AccountId}:accesspoint/${FinanaceAccessPointName}
            Condition:
              StringLike:
                s3:prefix:
                  - !Sub ${FinancePrefix}/*
          - Sid: ReadWriteForFinance
            Effect: Allow
            Principal:
              AWS:
                - !Ref FinanceUserArn
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
            Resource:
              - !Sub arn:${AWS::Partition}:s3:${AWS::Region}:${AWS::AccountId}:accesspoint/${FinanaceAccessPointName}/object/${FinancePrefix}/*
          - Sid: ExternalUserReadonly
            Effect: Allow
            Principal:
              AWS:
                - !GetAtt ExternalRole.Arn
            Action:
              - s3:GetObject
            Resource:
              - !Sub arn:${AWS::Partition}:s3:${AWS::Region}:${AWS::AccountId}:accesspoint/${FinanaceAccessPointName}/object/${FinancePrefix}/*

Outputs:
  SalesAccessArn:
    Description: Access point ARN for Sales
    Value: !GetAtt SalesAccessPoint.Arn
  SalesAccessAlias:
    Description: Access point alias for Sales
    Value: !GetAtt SalesAccessPoint.Alias
  FinanceAccessArn:
    Description: Access point ARN for Finance
    Value: !GetAtt FinanceAccessPoint.Arn
  FinanceAccessAlias:
    Description: Access point alias for Finance
    Value: !GetAtt FinanceAccessPoint.Alias
  ExternalRoleArn:
    Description: ARN for the External Role
    Value: !GetAtt ExternalRole.Arn
