AWSTemplateFormatVersion: 2010-09-09

Description: This configuration provisions a Route53 Failover routing policy.

Parameters:
  HostedZoneId:
    Type: String
    Description: Hosted zone ID
    Default: "Z00226231TM9RP3FCC7TD" # for my goodguys.click domain
  DomainName:
    Type: String
    Description: Hostname for the subdomain
    Default: geolocation.goodguys.click
  DefaultIp:
    Type: String
    Description: IP address for EC2 instance to serve as default
    Default: ""
  AfricaIp:
    Type: String
    Description: IP address for EC2 instance in af-south-1
    Default: ""
  AmericaIp:
    Type: String
    Description: IP address for EC2 instance in us-east-1
    Default: ""

Resources:
  # PrimaryHealth:
  #   Type: AWS::Route53::HealthCheck
  #   Properties:
  #     HealthCheckConfig:
  #       Type: HTTP
  #       IPAddress: !Ref DefaultIp
  #       Port: 80
  #       ResourcePath: /
  #       RequestInterval: 30
  #       FailureThreshold: 3
  #     HealthCheckTags:
  #       - Key: Name
  #         Value: PrimaryHealth

  DefaultRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref DomainName
      Type: A
      HostedZoneId: !Ref HostedZoneId
      # HealthCheckId: !Ref PrimaryHealth
      TTL: 60
      SetIdentifier: DefaultRecord
      ResourceRecords:
        - !Ref DefaultIp
      GeoLocation:
        CountryCode: "*"

  AfricaRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref DomainName
      Type: A
      HostedZoneId: !Ref HostedZoneId
      TTL: 60
      SetIdentifier: AfricaRecord
      ResourceRecords:
        - !Ref AfricaIp
      GeoLocation:
        ContinentCode: AF

  AmericaRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref DomainName
      Type: A
      HostedZoneId: !Ref HostedZoneId
      TTL: 60
      SetIdentifier: AmericaRecord
      ResourceRecords:
        - !Ref AmericaIp
      GeoLocation:
        CountryCode: US
