AWSTemplateFormatVersion: 2010-09-09

Description: Configures S3 event notification to SNS topic

Parameters:
  SubscriptionEmail:
    Type: String
    Description: Email address to subscribe to SNS topic
    Default: bbdchucks@gmail.com
  BucketName:
    Type: String
    Description: S3 bucket name
    AllowedValues: [simple-notification-04-2025]
    Default: simple-notification-04-2025

Resources:
  SimpleTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: SimpleTopic042025

  TopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref SimpleTopic
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowS3ToPublish
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sns:Publish
            Resource: !Ref SimpleTopic
            Condition:
              ArnLike:
                aws:SourceArn: !Sub arn:aws:s3:::${BucketName}
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId

  SimpleBucket:
    Type: AWS::S3::Bucket
    DependsOn: TopicPolicy
    Properties:
      BucketName: !Ref BucketName
      NotificationConfiguration:
        TopicConfigurations:
          - Event: s3:ObjectCreated:*
            Topic: !Ref SimpleTopic
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: images/
                  - Name: suffix
                    Value: .jpg

  Subscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref SimpleTopic
      Endpoint: !Ref SubscriptionEmail
