AWSTemplateFormatVersion: 2010-09-09

Description: A simple EC2 instance

Parameters:
  EnvName:
    Description: Name of the deployment environment
    Type: String
    AllowedValues:
      - Dev
      - Staging
      - Prod
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair
  ImageId:
    Description: The Amazon Image Id
    Type: String
    Default: ami-0abb41dc69b6b6704 # Amazon Linux 2 AMI 64-bit (x86)
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
  BucketArns:
    Description: S3 bucket ARNs
    Type: CommaDelimitedList

Resources:
  SimpleRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Ec2InstanceRole
      Description: An IAM role for EC2 instance
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: Ec2InstanceRolePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "s3:ListBucket"
                  - "s3:GetBucketPolicy"
                Resource: !Ref BucketArns
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                Resource:
                  - !Join ["", [!Select [0, !Ref BucketArns], "/*"]]
                  - !Join ["", [!Select [1, !Ref BucketArns], "/*"]]
              - Effect: Allow
                Action:
                  - "sns:ListTopics"
                Resource: "*"
  SimpleProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: Ec2InstanceProfile
      Path: /
      Roles:
        - !Ref SimpleRole
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${EnvName}SshAndHttpAccess"
      GroupDescription: Enable SSH access via port 22 and HTTP access on 80
      SecurityGroupIngress:
        - Description: Allow SSH access to all
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
        - Description: Allow HTTP access to all
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
      Tags:
        - Key: Name
          Value: Simple HTTP and SSH Access
  SimpleEc2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref SimpleProfile
      SecurityGroups:
        - !Ref WebSecurityGroup
      Tags:
        - Key: Name
          Value: Simple EC2 Instance
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Update the instance

          sudo yum update -y

          ## Install Nginx
          sudo amazon-linux-extras install nginx1 -y
          sudo service nginx start

          # Enable Nginx to start at Boot time
          sudo chkconfig nginx o

Outputs:
  SecurityGroupId:
    Description: Security group ID
    Value: !GetAtt WebSecurityGroup.GroupId
  InstanceId:
    Description: Instance ID of the created EC2 instance
    Value: !Ref SimpleEc2
  PublicDNS:
    Description: Public DNS name of the created EC2 instance
    Value: !GetAtt SimpleEc2.PublicDnsName
  PublicIP:
    Description: Public IP address of the created EC2 instance
    Value: !GetAtt SimpleEc2.PublicIp
