AWSTemplateFormatVersion: 2010-09-09

Description: A simple EC2 instance

Parameters:
  EnvName:
    Description: Name of the deployment environment
    Type: String
    AllowedValues:
      - Dev
      - Staging
      - Prod
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair
  ImageId:
    Description: The Amazon Image Id
    Type: String
    Default: "ami-0b2ed2e3df8cf9080" # Amazon Linux 2023 AMI 64-bit (x86)
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium

Resources:
  SshSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${EnvName}SshSecGp"
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
      Tags:
        - Key: Name
          Value: Simple SSH Access
  SimpleEc2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref SshSecurityGroup
      Tags:
        - Key: Name
          Value: Simple EC2 Instance

Outputs:
  InstanceId:
    Description: Instance ID of the created EC2 instance
    Value: !Ref SimpleEc2

  PublicDNS:
    Description: Public DNS name of the created EC2 instance
    Value: !GetAtt SimpleEc2.PublicDnsName

  PublicIP:
    Description: Public IP address of the created EC2 instance
    Value: !GetAtt SimpleEc2.PublicIp
