AWSTemplateFormatVersion: 2010-09-09

Description: Create a Trail to log all management events to a S3 bucket.

Resources:
  TrailBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: trail-bucket-18-05

  TrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TrailBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: TrailAclCheck
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !GetAtt TrailBucket.Arn
          - Sid: TrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub "${TrailBucket.Arn}/AWSLogs/*"
            Condition:
              StringEquals:
                "s3:x-amz-acl": "bucket-owner-full-control"

  Trail:
    Type: AWS::CloudTrail::Trail
    DependsOn: TrailBucketPolicy
    Properties:
      TrailName: SimpleMgtTrail
      S3BucketName: !Ref TrailBucket
      IsLogging: true
      IsMultiRegionTrail: false
      EnableLogFileValidation: true
      IncludeGlobalServiceEvents: true
# By default, trails created without specific EventSelector will be configured to
# log all read and write management events, and no data events.
