AWSTemplateFormatVersion: 2010-09-09

Description: Create two EC2 instances in different availability zones and attach an EBS volume to one of them.

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair
    Default: DevSimpleKey

Mappings:
  Images: # Amazon Linux 2023 AMI 64-bit (x86), uefi-preferred
    eu-west-1:
      Ami: ami-0720a3ca2735bf2fa
    eu-west-2:
      Ami: ami-04ba8620fc44e2264
    eu-west-3:
      Ami: ami-0960d166ab83fd695

Resources:
  InstanceSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: InstanceSecGroup
      GroupDescription: Enable SSH and HTTP access
      SecurityGroupIngress:
        - Description: Allow SSH access
          IpProtocol: TCP
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - Description: Allow HTTP access
          IpProtocol: TCP
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  InstanceA:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !FindInMap [Images, !Ref AWS::Region, Ami]
      KeyName: !Ref KeyName
      AvailabilityZone: !Sub ${AWS::Region}a
      SecurityGroupIds:
        - !GetAtt InstanceSecGroup.GroupId
      Tags:
        - Key: Name
          Value: WebServerA

  InstanceB:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !FindInMap [Images, !Ref AWS::Region, Ami]
      KeyName: !Ref KeyName
      AvailabilityZone: !Sub ${AWS::Region}b
      SecurityGroupIds:
        - !GetAtt InstanceSecGroup.GroupId
      Tags:
        - Key: Name
          Value: WebServerB

  EbsVolumeA:
    Type: AWS::EC2::Volume
    DeletionPolicy: Delete
    Properties:
      AvailabilityZone: !Sub ${AWS::Region}a
      VolumeType: gp3
      Size: 10
      Tags:
        - Key: Name
          Value: EbsVolumeA

  VolumeAttach:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      Device: /dev/sdf
      InstanceId: !Ref InstanceA
      VolumeId: !Ref EbsVolumeA

Outputs:
  InstanceAPublicIp:
    Description: Public IP for InstanceA
    Value: !GetAtt InstanceA.PublicIp
  InstanceBPublicIp:
    Description: Public IP for InstanceB
    Value: !GetAtt InstanceB.PublicIp
  InstanceBId:
    Description: Instance ID for InstanceB
    Value: !Ref InstanceB
    Export:
      Name: EbsVolumeA-InstanceBId
  VolumeAId:
    Description: Volume ID for VolumeA
    Value: !Ref EbsVolumeA
