AWSTemplateFormatVersion: 2010-09-09

Description: Cloudfront distribution with path based routing and request header modification

Parameters:
  ApiToken:
    Type: String
    Description: API token
  ApiEndpoint:
    Type: String
    Description: API endpoint
  DefaultOriginId:
    Type: String
    Description: A constant
    Default: DefaultOrigin
    AllowedValues:
      - DefaultOrigin
  ApiOriginId:
    Type: String
    Description: A constant
    Default: ApiOrigin
    AllowedValues:
      - ApiOrigin
  CachePolicyId:
    Type: String
    Description: Cache policy Id
    Default: 658327ea-f89d-4fab-a63d-7e88639e58f6 #cache optimized policy. To see other manages cache policies, go to CloudFront console > Policies > Cache
  FuncVersion:
    Type: String
    Description: Function version for CloudFront Function
    Default: 1

Resources:
  OriginBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: app-asset-bucket-14-feb-24

  OriginBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref OriginBucket
      PolicyDocument:
        Version: 2012-10-17
        Id: OriginBucketCloudFrontPolicy
        Statement:
          - Sid: AllowCloudFrontReadAccess
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub ${OriginBucket.Arn}/*
            Condition:
              StringEquals:
                aws:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${AppDistribution.Id} # arn:aws:cloudfront::314146339647:distribution/E3B10WTJ94206A # !GetAtt AppDistribution.Arn

  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: SimpleAccessCtl
        Description: Access Control to S3 bucket for CloudFront distribution
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontFunc:
    Type: AWS::CloudFront::Function
    Properties:
      Name: SimpleCloudFrontFunc
      AutoPublish: true
      FunctionConfig:
        Comment: Simple Func For App Distribution
        Runtime: cloudfront-js-2.0
      FunctionCode: !Sub |
        function handler(event) {
            const request = event.request;
            const uri = request.uri;  
            const token = "Bearer ${ApiToken}";
          
            request.headers["Authorization"] = { value: token };
            if (uri.startsWith('/simulation/api')) {
              request.uri = uri.replace('/simulation', '');
            }
            return request;
        }

  AppDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          TargetOriginId: !Ref DefaultOriginId
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: !Ref CachePolicyId
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - PATCH
            - POST
            - DELETE
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: true
        CacheBehaviors:
          - PathPattern: "/simulation/api/*"
            TargetOriginId: !Ref ApiOriginId
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - PATCH
              - POST
              - DELETE
            ForwardedValues:
              QueryString: true
            LambdaFunctionAssociations:
              - EventType: viewer-request
                LambdaFunctionARN: !Sub ${CloudFrontFunc.FunctionMetadata.FunctionARN}/${FuncVersion} # arn:aws:cloudfront::${AWS::AccountId}:function/CloudFrontFunc/${CloudFrontFunc.Version} #!GetAtt CloudFrontFunc.FunctionARN
        Origins:
          - Id: !Ref DefaultOriginId
            DomainName: !GetAtt OriginBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ""
            OriginAccessControlId: !GetAtt CloudFrontOAC.Id
          - Id: !Ref ApiOriginId
            DomainName: !Ref ApiEndpoint
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

Outputs:
  ApplicationUrl:
    Description: CloudFront distribution URL
    Value: !Sub https://${AppDistribution.DomainName}
