AWSTemplateFormatVersion: 2010-09-09

Description: Create EBS volume in another AZ from existing snapshot

Parameters:
  Az:
    Type: String
    Description: Availability zone
    Default: eu-west-2b
  SnapshotId:
    Type: String
    Description: SnapshotId
    # AllowedPattern: snap-[0-9a-zA-Z]
    Default: snap-082600691dc080332

Resources:
  EbsVolume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: !Ref Az
      SnapshotId: !Ref SnapshotId
      VolumeType: gp3
      Encrypted: true
      Tags:
        - Key: Name
          Value: SnapshotDemoVolume

Outputs:
  VolumeId:
    Description: EBS volumn ID
    Value: !Ref EbsVolume
