AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template to configure Secrets Manager and integrate with RDS MySQL"

Parameters:
  DBUsername:
    Type: String
    Default: admin
    NoEcho: true
    Description: Database master username

  DBPassword:
    Type: String
    NoEcho: true
    Description: Database master password

Resources:
  RdsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: "\"@/\\"

  RdsInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: demo-mysql-db
      Engine: mysql
      DBInstanceClass: db.t3.micro
      AllocatedStorage: "20"
      StorageType: gp2
      MasterUsername: !Sub "{{resolve:secretsmanager:${RdsSecret}::username}}"
      MasterUserPassword: !Sub "{{resolve:secretsmanager:${RdsSecret}::password}}"
      DBName: demodb
      MultiAZ: false

  RdsSecretRdsInstanceAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      TargetType: AWS::RDS::DBInstance
      SecretId: !Ref RdsSecret
      TargetId: !Ref RdsInstance

Outputs:
  RDSEndpoint:
    Description: RDS MySQL endpoint
    Value: !GetAtt RdsInstance.Endpoint.Address

  SecretArn:
    Description: Secrets Manager secret ARN
    Value: !GetAtt RdsSecret.Id

  SecretName:
    Description: Secrets Manager secret name
    Value: !Ref RdsSecret
