AWSTemplateFormatVersion: 2010-09-09

Description: Creates an Athena table for CloudTrail logs

Parameters:
  CloudTrailS3Bucket:
    Type: String
    Description: The S3 bucket name where the cloud trail logs is stored
    Default: dev-cloudtrail-storage
    # The CloudTrail logs should be in the standard format and location (s3://<bucket-name>/AWSLogs/<account-id>/CloudTrail/).

Resources:
  QueryResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub athena-query-results-${AWS::AccountId}-${AWS::Region}
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldResults
            Status: Enabled
            ExpirationInDays: 7

  AthenaWorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: CloudTrailLogsWorkGroup
      Description: WorkGroup for querying CloudTrail logs
      WorkGroupConfiguration:
        ResultConfiguration:
          OutputLocation: !Sub s3://${QueryResultsBucket}/

  GlueDbForCloudTrailData:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: cloudtrail_logs_db

  CloudTrailGlueTable:
    Type: AWS::Glue::Table
    Properties:
      DatabaseName: !Ref GlueDbForCloudTrailData
      CatalogId: !Ref AWS::AccountId
      TableInput:
        Name: cloudtrail_logs
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: cloudtrail # or  parquet
        StorageDescriptor:
          Columns:
            - Name: eventVersion
              Type: string
            - Name: userIdentity
              Type: "struct<type:string,principalId:string,arn:string,accountId:string,invokedBy:string,accessKeyId:string,userName:string,sessionContext:struct<attributes:struct<mfaAuthenticated:string,creationDate:string>,sessionIssuer:struct<type:string,principalId:string,arn:string,accountId:string,username:string>,ec2RoleDelivery:string,webIdFederationData:struct<federatedProvider:string,attributes:map<string,string>>>>"
            - Name: eventTime
              Type: string
            - Name: eventSource
              Type: string
            - Name: eventName
              Type: string
            - Name: awsRegion
              Type: string
            - Name: sourceIPAddress
              Type: string
            - Name: userAgent
              Type: string
            - Name: errorCode
              Type: string
            - Name: errorMessage
              Type: string
            - Name: requestParameters
              Type: string
            - Name: responseElements
              Type: string
            - Name: additionalEventData
              Type: string
            - Name: requestId
              Type: string
            - Name: eventId
              Type: string
            - Name: resources
              Type: "array<struct<arn:string,accountId:string,type:string>>"
            - Name: eventType
              Type: string
            - Name: apiVersion
              Type: string
            - Name: readOnly
              Type: string
            - Name: recipientAccountId
              Type: string
            - Name: serviceEventDetails
              Type: string
            - Name: sharedEventID
              Type: string
            - Name: vpcEndpointId
              Type: string
            - Name: tlsDetails
              Type: "struct<tlsVersion:string,cipherSuite:string,clientProvidedHostHeader:string>"
          Location: !Sub "s3://${CloudTrailS3Bucket}/AWSLogs/${AWS::AccountId}/CloudTrail/"
          InputFormat: com.amazon.emr.cloudtrail.CloudTrailInputFormat # or org.apache.hadoop.mapred.TextInputForma
          OutputFormat: "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
          SerdeInfo:
            SerializationLibrary: "org.apache.hive.hcatalog.data.JsonSerDe"

Outputs:
  QueryResultsBucketName:
    Description: "Name of the S3 bucket to store Athena query results"
    Value: !Ref QueryResultsBucket
  AthenaWorkGroupName:
    Description: "Name of the Athena WorkGroup"
    Value: !Ref AthenaWorkGroup
  GlueDatabaseName:
    Description: "Name of the Athena Database"
    Value: !Ref GlueDbForCloudTrailData
  GlueTableName:
    Description: "Name of the Athena Table for CloudTrail logs"
    Value: !Ref CloudTrailGlueTable
