AWSTemplateFormatVersion: 2010-09-09

Description: Creates an S3 table to be used on Athena Console

Resources:
  AthenaResultBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: athena-results-08-02-25
