AWSTemplateFormatVersion: 2010-09-09

Description: This template demonstrates the use of Athena to query data on an S3 bucket

Resources:
  AthenaResultBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: athena-results-08-02-25

  AthenaGlueDb:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: athena_database
        Description: Glue database for Athena queries

  AthenaGlueTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref AthenaGlueDb
      TableInput:
        Name: athena_table
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: parquet
        StorageDescriptor:
          Location: !Sub s3://${AthenaResultBucket}/data/
          InputFormat: "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat"
          OutputFormat: "org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat"
          SerdeInfo:
            SerializationLibrary: "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe"
          Columns:
            - Name: id
              Type: int
            - Name: name
              Type: string
            - Name: age
              Type: int
