AWSTemplateFormatVersion: 2010-09-09

Description: This template configures a Network Load Balancer that distributes traffic to a target group with two EC2 instances

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Vpc Id
    Default: vpc-097728e00a72ac827 # Default VPC
  SubnetId1:
    Type: AWS::EC2::Subnet::Id
    Description: First subnet Id in the Vpc provided
    Default: subnet-01e6764eb590a6eb3 # Default Subnet 1
  SubnetId2:
    Type: AWS::EC2::Subnet::Id
    Description: Second subnet Id in the Vpc provided
    Default: subnet-08e8eaec953c85086 # Default Subnet 2
  InstanceType:
    Type: String
    Description: EC2 instance type
    AllowedValues:
      - t2.micro
      - t3.micro
    Default: t2.micro
  ImageId:
    Type: String
    Description: Amazon Machine Image
    Default: ami-0abb41dc69b6b6704 # Amazon Linux 2 AMI 64-bit (x86)
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 Keypair name
    Default: DevSimpleKey
  TemplateBucket:
    Type: String
    Description: S3 bucket where child templates are stored
    Default: chucks-workspace-storage

Resources:
  NlbSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: NlbSecGroup
      GroupDescription: Application Load Balancer security group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - Description: Allows HTTP access
          IpProtocol: TCP
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: WebSecGroup
      GroupDescription: Web server security group SSH and HTTP
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - Description: Allow SSH access to all
          IpProtocol: TCP
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - Description: Allow HTTP traffic originating from NlbSecGroup only
          IpProtocol: TCP
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !GetAtt NlbSecGroup.GroupId

  Ec2Instance1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/templates/NlbEc2Child.yaml
      Parameters:
        InstanceType: !Ref InstanceType
        ImageId: !Ref ImageId
        KeyName: !Ref KeyName
        SubnetId: !Ref SubnetId1
        WebSecGroup: !Ref WebSecGroup
        TagName: DemoInstance1

  Ec2Instance2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/templates/NlbEc2Child.yaml
      Parameters:
        InstanceType: !Ref InstanceType
        ImageId: !Ref ImageId
        KeyName: !Ref KeyName
        SubnetId: !Ref SubnetId2
        WebSecGroup: !Ref WebSecGroup
        TagName: DemoInstance2

  NlbTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: SimpleTarget
      TargetType: instance
      Protocol: TCP
      Port: 80
      VpcId: !Ref VpcId
      # HealthCheckProtocol: TCP
      HealthCheckProtocol: HTTP
      HealthCheckPort: traffic-port
      Targets:
        - Id: !GetAtt Ec2Instance1.Outputs.InstanceId
        - Id: !GetAtt Ec2Instance2.Outputs.InstanceId
      Tags:
        - Key: Name
          Value: NlbDemoTargetGroup

  NlbBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: SimpleNlBalancer
      Type: network
      Scheme: internet-facing
      Subnets:
        - !Ref SubnetId1
        - !Ref SubnetId2
      SecurityGroups:
        - !Ref NlbSecGroup
      Tags:
        - Key: Name
          Value: NlbDemoBalancer

  NlbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref NlbBalancer
      Protocol: TCP
      Port: 80
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref NlbTargetGroup

Outputs:
  LoadBalancerDns:
    Description: DNS name of the ALB
    Value: !GetAtt NlbBalancer.DNSName
  InstanceId1:
    Description: First EC2 instance ID
    Value: !GetAtt Ec2Instance1.Outputs.InstanceId
  InstanceId2:
    Description: Second EC2 instance ID
    Value: !GetAtt Ec2Instance2.Outputs.InstanceId
