AWSTemplateFormatVersion: 2010-09-09

Description: This template configures and EC2 instance on a different region to act as a client

Parameters:
  InstanceType:
    Type: String
    Description: EC2 Instance type
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Existing EC2 key-pair keyname
    Default: "" # Create key in eu-west-1

Mappings:
  Images: # Amazon Linux 2023 AMI 64-bit (x86), uefi-preferred
    eu-west-1:
      Ami: ami-0720a3ca2735bf2fa
    eu-west-2:
      Ami: ami-04ba8620fc44e2264
    eu-west-3:
      Ami: ami-0960d166ab83fd695

Resources:
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SimpleSshSG
      GroupDescription: Security group for SSH access only
      SecurityGroupIngress:
        - Description: Allow SSH from anywhere
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  ClientInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
