AWSTemplateFormatVersion: 2010-09-09

Description: Create a DynamoDB Global Table

Resources:
  Table:
    Type: AWS::DynamoDB::GlobalTable
    Properties:
      TableName: eStore
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: "NEW_AND_OLD_IMAGES"
      AttributeDefinitions:
        - AttributeName: clientid
          AttributeType: S
        - AttributeName: createdat
          AttributeType: S
      KeySchema:
        - AttributeName: clientid
          KeyType: HASH # Hash is Partition key
        - AttributeName: createdat
          KeyType: RANGE # Range is Sort key
      Replicas:
        - Region: eu-west-2 # Primary region
        - Region: eu-west-1 # First replica region
        - Region: eu-west-3 # Second replica region
