AWSTemplateFormatVersion: 2010-09-09

Description: This template configures an EC2 instance using an Amazon Linux 2 AMI

Parameters:
  ImageId:
    Type: String
    Description: AWS AMI ID
    Default: ami-0abb41dc69b6b6704 # Amazon Linux 2 AMI 64-bit (x86)
  InstanceType:
    Type: String
    Description: AWS instance type
    AllowedPattern: t[2-3].(micro)
    Default: t2.micro

Resources:
  WebSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: WebSecGroup
      GroupDescription: Allows HTTP access
      SecurityGroupIngress:
        - Description: Allow HTTP access from anywhere
          IpProtocol: TCP
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"

  SimpleInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref WebSecGroup
      Tags:
        - Key: Name
          Value: AmiDemoInstance
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Update the instance
          sudo yum update -y

          ## Install Nginx
          sudo amazon-linux-extras install nginx1 -y
          sudo service nginx start

          # Enable Nginx to start at Boot time
          sudo chkconfig nginx o

Outputs:
  PublicIp:
    Description: EC2 instance public ip
    Value: !GetAtt SimpleInstance.PublicIp
  PublicDnsName:
    Description: EC2 public DNS name
    Value: !GetAtt SimpleInstance.PublicDnsName
  InstanceId:
    Description: EC2 instance ID
    Value: !Ref SimpleInstance
