AWSTemplateFormatVersion: 2010-09-09

Description: Configuration creates a CloutTrail Trail to log events to an S3 bucket and CloudWatch Log
# This configuration uses EventSelectors properties instead of AdvancedEventSelectors  for the Trail confoguration

Resources:
  LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: trail-logs-04-2
      LifecycleConfiguration:
        Rules:
          - Id: ExpiresIn90d
            Status: Enabled
            ExpirationInDays: 90

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LogBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowGetAcl
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !GetAtt LogBucket.Arn
          - Sid: AllowPutObject
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub ${LogBucket.Arn}/*

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/trail/DemoEventLogs2
      RetentionInDays: 90

  CloudTrailRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CloudTrailRole2
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SimpleCloudTrailPolicy2
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: AllowCloudTrailLogs
                Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !GetAtt LogGroup.Arn

  SimpleTrail:
    Type: AWS::CloudTrail::Trail
    Properties:
      TrailName: DemoTrail2
      IsLogging: true
      EnableLogFileValidation: true
      IncludeGlobalServiceEvents: true
      IsMultiRegionTrail: true
      IsOrganizationTrail: false
      CloudWatchLogsRoleArn: !GetAtt CloudTrailRole.Arn
      CloudWatchLogsLogGroupArn: !GetAtt LogGroup.Arn
      S3BucketName: !Ref LogBucket
      S3KeyPrefix: cloud-trail-logs/
      EventSelectors:
        - IncludeManagementEvents: true
          ReadWriteType: All
          DataResources:
            - Type: AWS::Lambda::Function
              Values:
                - "arn:aws:lambda" # Logs all Lambda invocations
            - Type: AWS::DynamoDB::Table
              Values:
                - "arn:aws:dynamodb" # Logs DynamoDB item-level activity

